import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "reddit-cl/components/Header";
import PostBox from "reddit-cl/components/PostBox";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="max-w-5xl mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostBox />
    </div>
  );
}
